name: maven Github Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: Run test for maven
    runs-on: ubuntu-latest
    steps:
      - name: get source code
        uses: actions/checkout@v6
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: running tests
        run: mvn test 
  build:
    needs: test
    name: building maven
    runs-on: ubuntu-latest
    outputs:
      artifact-data: ${{ steps.artifact-name.outputs.artifact-data }}
    steps:
      - name: get source code
        uses: actions/checkout@v6
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: building jar artifacts file
        run: mvn clean package
      - name: upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifact-data
          path: 'target/*.jar'
      - name: Get the name of the output file
        id: artifact-name
        run: find target/*.jar -type f -execdir echo 'artifact-data={}' >> $GITHUB_OUTPUT ';'
        
  deploy:
    needs: build
    name: taking artifacts of maven
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts data from build jobs
        uses: actions/download-artifact@v7
        with:
          name: artifact-data
      - name: list my artifact
        run: ls
      - name: getting artifact file name
        run: echo ${{ needs.build.outputs.artifact-data }}