name: maven Github Actions
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    name: Run test for maven
    runs-on: ubuntu-latest
    steps:
      - name: get source code
        uses: actions/checkout@v6
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: running tests
        run: mvn test 
  build:
    needs: test
    name: building maven
    runs-on: ubuntu-latest
    steps:
      - name: get source code
        uses: actions/checkout@v6
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: building jar file
        run: mvn clean package
      - name: upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: artifact-data
          path: 'target/*.jar'